spring:
  application:
    name: chamaa-api
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/chamaa_db
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.chamaa: DEBUG
